
#define PIN_RX_SPEED 4
#define PIN_RX_STEER 3

#define PIN_U_SPEED 6
#define PIN_U_STEER 5
#define PIN_PING_TRIG 17
#define PIN_PING_ECHO 32

#define PIN_ODOMETER_FRONT_LEFT_SENSOR_A 8
#define PIN_ODOMETER_FRONT_LEFT_SENSOR_B 25

#define PIN_ODOMETER_FRONT_RIGHT_SENSOR_A 26
#define PIN_ODOMETER_FRONT_RIGHT_SENSOR_B 9

// "A" means toward front
#define PIN_ODOMETER_BACK_LEFT_SENSOR_A 10
#define PIN_ODOMETER_BACK_LEFT_SENSOR_B 27
#define PIN_ODOMETER_BACK_RIGHT_SENSOR_A 28
#define PIN_ODOMETER_BACK_RIGHT_SENSOR_B 11

#define PIN_MOTOR_RPM 29

#define PIN_SPEAKER   30
#define PIN_LED 13

#define PIN_BATTERY_VOLTAGE_DIVIDER 14

#define PIN_MPU_INTERRUPT 33


